// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from 'vue'
import { defineSliceZoneComponents } from '@prismicio/vue'

export const components = defineSliceZoneComponents({
  button: defineAsyncComponent(() => import('./Button/index.vue')),
  creator_team: defineAsyncComponent(() => import('./CreatorTeam/index.vue')),
  feature: defineAsyncComponent(() => import('./Feature/index.vue')),
  footer_menu: defineAsyncComponent(() => import('./FooterMenu/index.vue')),
  header_menu: defineAsyncComponent(() => import('./HeaderMenu/index.vue')),
  hero: defineAsyncComponent(() => import('./Hero/index.vue')),
  product_type: defineAsyncComponent(() => import('./ProductType/index.vue')),
  simple_content: defineAsyncComponent(
    () => import('./SimpleContent/index.vue')
  )
})
