// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from '@prismicio/types'
import type * as prismic from '@prismicio/client'

type Simplify<T> = {
  [KeyType in keyof T]: T[KeyType]
}
/** Content for MainFooter documents */
interface MainfooterDocumentData {
  /**
   * Slice Zone field in *MainFooter*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: mainfooter.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismicT.SliceZone<MainfooterDocumentDataSlicesSlice>
}
/**
 * Slice for *MainFooter → Slice Zone*
 *
 */
type MainfooterDocumentDataSlicesSlice = FooterMenuSlice
/**
 * MainFooter document from Prismic
 *
 * - **API ID**: `mainfooter`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MainfooterDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithoutUID<
    Simplify<MainfooterDocumentData>,
    'mainfooter',
    Lang
  >
/** Content for MainHeader documents */
interface MainheaderDocumentData {
  /**
   * Logo field in *MainHeader*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: mainheader.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  logo: prismicT.ImageField<never>
  /**
   * Logo Name field in *MainHeader*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mainheader.logo_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  logo_name: prismicT.KeyTextField
  /**
   * Slice Zone field in *MainHeader*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: mainheader.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismicT.SliceZone<MainheaderDocumentDataSlicesSlice>
}
/**
 * Slice for *MainHeader → Slice Zone*
 *
 */
type MainheaderDocumentDataSlicesSlice = HeaderMenuSlice | ButtonSlice
/**
 * MainHeader document from Prismic
 *
 * - **API ID**: `mainheader`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MainheaderDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithoutUID<
    Simplify<MainheaderDocumentData>,
    'mainheader',
    Lang
  >
/** Content for Page documents */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField
  /**
   * Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.desc
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  desc: prismicT.KeyTextField
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismicT.SliceZone<PageDocumentDataSlicesSlice>
}
/**
 * Slice for *Page → Slice Zone*
 *
 */
type PageDocumentDataSlicesSlice =
  | HeroSlice
  | SimpleContentSlice
  | ProductTypeSlice
  | CreatorTeamSlice
/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithUID<Simplify<PageDocumentData>, 'page', Lang>
export type AllDocumentTypes =
  | MainfooterDocument
  | MainheaderDocument
  | PageDocument
/**
 * Primary content in Button → Primary
 *
 */
interface ButtonSliceDefaultPrimary {
  /**
   * Label field in *Button → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: button.primary.label
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  label: prismicT.KeyTextField
  /**
   * Icon Code field in *Button → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: button.primary.icon_code
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  icon_code: prismicT.KeyTextField
  /**
   * Link field in *Button → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: button.primary.link
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  link: prismicT.LinkField
}
/**
 * Default variation for Button Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ButtonSliceDefault = prismicT.SharedSliceVariation<
  'default',
  Simplify<ButtonSliceDefaultPrimary>,
  never
>
/**
 * Slice variation for *Button*
 *
 */
type ButtonSliceVariation = ButtonSliceDefault
/**
 * Button Shared Slice
 *
 * - **API ID**: `button`
 * - **Description**: `Button`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ButtonSlice = prismicT.SharedSlice<'button', ButtonSliceVariation>
/**
 * Primary content in CreatorTeam → Primary
 *
 */
interface CreatorTeamSliceDefaultPrimary {
  /**
   * Heading field in *CreatorTeam → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: creator_team.primary.heading
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  heading: prismicT.KeyTextField
  /**
   * Content field in *CreatorTeam → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: creator_team.primary.content
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  content: prismicT.RichTextField
}
/**
 * Item in CreatorTeam → Items
 *
 */
export interface CreatorTeamSliceDefaultItem {
  /**
   * Avatar field in *CreatorTeam → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: creator_team.items[].avatar
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  avatar: prismicT.ImageField<never>
  /**
   * Name field in *CreatorTeam → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: creator_team.items[].name
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  name: prismicT.KeyTextField
  /**
   * About field in *CreatorTeam → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: creator_team.items[].about
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  about: prismicT.RichTextField
  /**
   * Role field in *CreatorTeam → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: creator_team.items[].role
   * - **Documentation**: https://prismic.io/docs/core-concepts/select
   *
   */
  role: prismicT.SelectField<
    'Founder' | 'Developer' | 'Designer' | 'Contributor'
  >
}
/**
 * Default variation for CreatorTeam Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CreatorTeamSliceDefault = prismicT.SharedSliceVariation<
  'default',
  Simplify<CreatorTeamSliceDefaultPrimary>,
  Simplify<CreatorTeamSliceDefaultItem>
>
/**
 * Slice variation for *CreatorTeam*
 *
 */
type CreatorTeamSliceVariation = CreatorTeamSliceDefault
/**
 * CreatorTeam Shared Slice
 *
 * - **API ID**: `creator_team`
 * - **Description**: `CreatorTeam`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CreatorTeamSlice = prismicT.SharedSlice<
  'creator_team',
  CreatorTeamSliceVariation
>
/**
 * Default variation for Feature Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FeatureSliceDefault = prismicT.SharedSliceVariation<
  'default',
  Record<string, never>,
  never
>
/**
 * Slice variation for *Feature*
 *
 */
type FeatureSliceVariation = FeatureSliceDefault
/**
 * Feature Shared Slice
 *
 * - **API ID**: `feature`
 * - **Description**: `Feature`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FeatureSlice = prismicT.SharedSlice<
  'feature',
  FeatureSliceVariation
>
/**
 * Primary content in FooterMenu → Primary
 *
 */
interface FooterMenuSliceDefaultPrimary {
  /**
   * Heading field in *FooterMenu → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_menu.primary.heading
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  heading: prismicT.KeyTextField
}
/**
 * Item in FooterMenu → Items
 *
 */
export interface FooterMenuSliceDefaultItem {
  /**
   * Label field in *FooterMenu → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_menu.items[].label
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  label: prismicT.KeyTextField
  /**
   * Path field in *FooterMenu → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_menu.items[].path
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  path: prismicT.KeyTextField
}
/**
 * Default variation for FooterMenu Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FooterMenuSliceDefault = prismicT.SharedSliceVariation<
  'default',
  Simplify<FooterMenuSliceDefaultPrimary>,
  Simplify<FooterMenuSliceDefaultItem>
>
/**
 * Slice variation for *FooterMenu*
 *
 */
type FooterMenuSliceVariation = FooterMenuSliceDefault
/**
 * FooterMenu Shared Slice
 *
 * - **API ID**: `footer_menu`
 * - **Description**: `FooterMenu`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FooterMenuSlice = prismicT.SharedSlice<
  'footer_menu',
  FooterMenuSliceVariation
>
/**
 * Item in HeaderMenu → Items
 *
 */
export interface HeaderMenuSliceDefaultItem {
  /**
   * Icon Code field in *HeaderMenu → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_menu.items[].icon_code
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  icon_code: prismicT.KeyTextField
  /**
   * Label field in *HeaderMenu → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_menu.items[].label
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  label: prismicT.KeyTextField
  /**
   * Link field in *HeaderMenu → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_menu.items[].link
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  link: prismicT.KeyTextField
}
/**
 * Default variation for HeaderMenu Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeaderMenuSliceDefault = prismicT.SharedSliceVariation<
  'default',
  Record<string, never>,
  Simplify<HeaderMenuSliceDefaultItem>
>
/**
 * Slice variation for *HeaderMenu*
 *
 */
type HeaderMenuSliceVariation = HeaderMenuSliceDefault
/**
 * HeaderMenu Shared Slice
 *
 * - **API ID**: `header_menu`
 * - **Description**: `HeaderMenu`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeaderMenuSlice = prismicT.SharedSlice<
  'header_menu',
  HeaderMenuSliceVariation
>
/**
 * Primary content in Hero → Primary
 *
 */
interface HeroSliceDefaultPrimary {
  /**
   * Heading field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.heading
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  heading: prismicT.KeyTextField
  /**
   * Heading Accent field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.heading_accent
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  heading_accent: prismicT.KeyTextField
  /**
   * Background Image field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.background_image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  background_image: prismicT.ImageField<never>
}
/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSliceDefault = prismicT.SharedSliceVariation<
  'default',
  Simplify<HeroSliceDefaultPrimary>,
  never
>
/**
 * Slice variation for *Hero*
 *
 */
type HeroSliceVariation = HeroSliceDefault
/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: `Hero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSlice = prismicT.SharedSlice<'hero', HeroSliceVariation>
/**
 * Primary content in ProductType → Primary
 *
 */
interface ProductTypeSliceDefaultPrimary {
  /**
   * Heading field in *ProductType → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_type.primary.heading
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  heading: prismicT.KeyTextField
  /**
   * Content field in *ProductType → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_type.primary.content
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  content: prismicT.RichTextField
}
/**
 * Item in ProductType → Items
 *
 */
export interface ProductTypeSliceDefaultItem {
  /**
   * Icon field in *ProductType → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_type.items[].icon
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  icon: prismicT.KeyTextField
  /**
   * Name field in *ProductType → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_type.items[].name
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  name: prismicT.KeyTextField
  /**
   * Description field in *ProductType → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_type.items[].desc
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  desc: prismicT.RichTextField
}
/**
 * Default variation for ProductType Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProductTypeSliceDefault = prismicT.SharedSliceVariation<
  'default',
  Simplify<ProductTypeSliceDefaultPrimary>,
  Simplify<ProductTypeSliceDefaultItem>
>
/**
 * Slice variation for *ProductType*
 *
 */
type ProductTypeSliceVariation = ProductTypeSliceDefault
/**
 * ProductType Shared Slice
 *
 * - **API ID**: `product_type`
 * - **Description**: `ProductType`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ProductTypeSlice = prismicT.SharedSlice<
  'product_type',
  ProductTypeSliceVariation
>
/**
 * Primary content in SimpleContent → Primary
 *
 */
interface SimpleContentSliceDefaultPrimary {
  /**
   * Heading field in *SimpleContent → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: simple_content.primary.heading
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  heading: prismicT.KeyTextField
  /**
   * Content field in *SimpleContent → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: simple_content.primary.content
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  content: prismicT.RichTextField
  /**
   * Background Color field in *SimpleContent → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: simple_content.primary.background_color
   * - **Documentation**: https://prismic.io/docs/core-concepts/color
   *
   */
  background_color: prismicT.ColorField
}
/**
 * Default variation for SimpleContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SimpleContentSliceDefault = prismicT.SharedSliceVariation<
  'default',
  Simplify<SimpleContentSliceDefaultPrimary>,
  never
>
/**
 * Primary content in SimpleContent → Primary
 *
 */
interface SimpleContentSliceSideSideLayoutPrimary {
  /**
   * Heading field in *SimpleContent → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: simple_content.primary.heading
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  heading: prismicT.KeyTextField
  /**
   * Content field in *SimpleContent → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: simple_content.primary.content
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  content: prismicT.RichTextField
  /**
   * Background Color field in *SimpleContent → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: simple_content.primary.background_color
   * - **Documentation**: https://prismic.io/docs/core-concepts/color
   *
   */
  background_color: prismicT.ColorField
}
/**
 * Side Side Layout variation for SimpleContent Slice
 *
 * - **API ID**: `sideSideLayout`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SimpleContentSliceSideSideLayout = prismicT.SharedSliceVariation<
  'sideSideLayout',
  Simplify<SimpleContentSliceSideSideLayoutPrimary>,
  never
>
/**
 * Slice variation for *SimpleContent*
 *
 */
type SimpleContentSliceVariation =
  | SimpleContentSliceDefault
  | SimpleContentSliceSideSideLayout
/**
 * SimpleContent Shared Slice
 *
 * - **API ID**: `simple_content`
 * - **Description**: `SimpleContent`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SimpleContentSlice = prismicT.SharedSlice<
  'simple_content',
  SimpleContentSliceVariation
>
declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>
  }
  namespace Content {
    export type {
      MainfooterDocumentData,
      MainfooterDocumentDataSlicesSlice,
      MainfooterDocument,
      MainheaderDocumentData,
      MainheaderDocumentDataSlicesSlice,
      MainheaderDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      PageDocument,
      AllDocumentTypes,
      ButtonSliceDefaultPrimary,
      ButtonSliceDefault,
      ButtonSliceVariation,
      ButtonSlice,
      CreatorTeamSliceDefaultPrimary,
      CreatorTeamSliceDefaultItem,
      CreatorTeamSliceDefault,
      CreatorTeamSliceVariation,
      CreatorTeamSlice,
      FeatureSliceDefault,
      FeatureSliceVariation,
      FeatureSlice,
      FooterMenuSliceDefaultPrimary,
      FooterMenuSliceDefaultItem,
      FooterMenuSliceDefault,
      FooterMenuSliceVariation,
      FooterMenuSlice,
      HeaderMenuSliceDefaultItem,
      HeaderMenuSliceDefault,
      HeaderMenuSliceVariation,
      HeaderMenuSlice,
      HeroSliceDefaultPrimary,
      HeroSliceDefault,
      HeroSliceVariation,
      HeroSlice,
      ProductTypeSliceDefaultPrimary,
      ProductTypeSliceDefaultItem,
      ProductTypeSliceDefault,
      ProductTypeSliceVariation,
      ProductTypeSlice,
      SimpleContentSliceDefaultPrimary,
      SimpleContentSliceDefault,
      SimpleContentSliceSideSideLayoutPrimary,
      SimpleContentSliceSideSideLayout,
      SimpleContentSliceVariation,
      SimpleContentSlice
    }
  }
}
