# Preview Deployment
#
# Allow to push every code into a preview environment in vercel
# so team can easily to preview the current result on each branch

# ======= NOTE ======
# This deployment is always work on other branch excepts the main

name: Preview Deployment to Vercel

env:
  VERCEL_ORG_ID: ${{secrets.VERCEL_ORG_ID}}
  VERCEL_PROJECT_ID: ${{secrets.VERCEL_PROJECT_ID}}

on:
  push:
    branches-ignore:
      - main

jobs:
  Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pull Vercel Environment Information
        run: npx vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: npx vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: npx vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
